### ISSUE TITLE
Links to product pages?

### ISSUE THREAD

**Issue by DennisSuitters** [openrazer/openrazer.github.io#13]
Firstly, thanks for this project as a whole, I'm not sure why I hadn't discovered this sooner as I've been looking for a long time for a way to administer settings in Linux for my Razor Products (lol, they've never been touched by Microsoft).

I was wondering if there were plans to link out to the product pages on the Razor Website, which I believe would make checking out products more easily, as I noticed there's a few I wouldn't mind purchasing or upgrading too myself. I guess it's just me being lazy, just thought it would be a handy feature.

I another thought I just had, like with the WINE website they indicate in percentage how complete or how compatible something is, as I assume not all of the hardware works 100%, and that may help user's of your project as to why a feature they are trying to get to work, isn't, as it's not 100% working. It might save someone spending hours, days, or weeks of frustration, when they could simply see that a certain feature is being worked on or not.

Anyway, again, thanks for the project. If there's anyway I can help support or enrich the project (adding the links for e.g.), let me know.

**Comment by lah7** [comment]
Thanks for the suggestions! We did historically (around 2017?) link to the Razer store pages when the daemon stored URLs for them. These were likely dropped because it became a maintenance burden (for little benefit) as well as the inconsistency of some devices no longer having a Razer page to link any more or getting 404'd.

In terms of compatibility, it is expected that the devices added to the project support all of their hardware features (tested by the community). Hunting the [issue tracker](https://github.com/openrazer/openrazer/issues) by label (`bug`, `enhancement`, `help wanted`) would provide a more reliable status report then manually updating a [wiki page](https://github.com/openrazer/openrazer/wiki). It's also tricky because "device issues" may in fact be an issue in specific frontends, which isn't OpenRazer's responsibility.

Glad you like the project! :+1:
